import { MigrationInterface, QueryRunner } from "typeorm";

import { Campo } from "src/application/tramite/entities/parametricas/campo.entity";
import { Seccion } from "src/application/tramite/entities/parametricas/seccion.entity"; 

import { Status } from 'src/common/constants/index';

export class Campo1643292407929 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        const items = [
            {
                id: 1,
                campo: 'tipo_unidad_economica',
                tipo: 'text',
                label: 'tipo de unidad economica',
                tooltip: 'tipo de unidad economica',
                orden: 1,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: ['required', 'caracteresEspeciales'],
                parametrica: null,
                filtro: null,
                maxMinFecha: null,
                size: 4,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: false,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 1
            },
            {
                id: 2,
                campo: 'objeto_social',
                tipo: 'text',
                label: 'objeto social',
                tooltip: 'objeto social',
                orden: 2,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: ['required'],
                parametrica: null,
                filtro: null,
                maxMinFecha: null,
                size: 4,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: false,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 1
            },
            {
                id: 3,
                campo: 'departamentos',
                tipo: 'select',
                label: 'Departamentos',
                tooltip: 'departamentos',
                orden: 3,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: ['required'],
                parametrica: 'parametros/departamentos',
                parametricaText: 'nombre',
                filtro: null,
                maxMinFecha: null,
                size: 4,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: false,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 2
            },
            {
                id: 4,
                campo: 'fecha',
                tipo: 'date',
                label: 'Fecha',
                tooltip: 'fecha',
                orden: 3,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: ['required'],
                filtro: null,
                maxMinFecha: null,
                size: 4,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: false,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 2
            },
            {
                id: 5,
                campo: 'nro_documento',
                tipo: 'text',
                label: 'numero docuemnto',
                tooltip: 'numero documento',
                orden: 4,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: ['required', 'nro_documento'],
                parametrica: null,
                filtro: null,
                maxMinFecha: null,
                size: 4,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: false,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 2
            },
            {
                id: 6,
                campo: 'certificado',
                tipo: 'file',
                label: 'certificado prueba',
                tooltip: 'certificado prueba',
                orden: 4,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: ['required'],
                parametrica: null,
                filtro: null,
                maxMinFecha: null,
                size: 3,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: true,
                codigoTipoDocumento: 'COD-D1',
                criterioOpcional: null,
                seccion: 5
            },
            {
                id: 7,
                campo: 'certificado_nro_documento',
                tipo: 'text',
                label: 'Numero de documento',
                tooltip: 'Numero de documento',
                orden: 1,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: ['required', 'validateLongitudNit'],
                parametrica: null,
                filtro: null,
                maxMinFecha: null,
                size: 3,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: true,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 5
            },
            {
                id: 8,
                campo: 'certificado_emisor',
                tipo: 'text',
                label: 'emisor',
                tooltip: 'emisor',
                orden: 2,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: ['required'],
                parametrica: null,
                filtro: null,
                maxMinFecha: null,
                size: 3,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: true,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 5
            },
            {
                id: 9,
                campo: 'certificado_fecha_emision',
                tipo: 'date',
                label: 'fecha emision',
                tooltip: 'fecha emision',
                orden: 3,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: null,
                parametrica: null,
                filtro: null,
                maxMinFecha: null,
                size: 3,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: true,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 5
            },
            {
                id: 10,
                campo: 'certificado2',
                tipo: 'file',
                label: 'certificado prueba',
                tooltip: 'certificado prueba',
                orden: 8,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: null,
                parametrica: null,
                filtro: null,
                maxMinFecha: null,
                size: 3,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: true,
                codigoTipoDocumento: 'COD-D2',
                criterioOpcional: null,
                seccion: 5
            },
            {
                id: 11,
                campo: 'certificado2_nro_documento',
                tipo: 'text',
                label: 'Numero de documento',
                tooltip: 'Numero de documento',
                orden: 5,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: null,
                parametrica: null,
                filtro: null,
                maxMinFecha: null,
                size: 3,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: true,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 5
            },
            {
                id: 12,
                campo: 'certificado2_emisor',
                tipo: 'text',
                label: 'emisor',
                tooltip: 'emisor',
                orden: 6,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: null,
                parametrica: null,
                filtro: null,
                maxMinFecha: null,
                size: 3,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: true,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 5
            },
            {
                id: 13,
                campo: 'certificado2_fecha_emision',
                tipo: 'date',
                label: 'fecha emision',
                tooltip: 'fecha emision',
                orden: 7,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: null,
                parametrica: null,
                filtro: null,
                maxMinFecha: null,
                size: 3,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: true,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 5
            },
            {
                id: 71,
                campo: 'email',
                tipo: 'correo',
                label: 'Correo electrónico del establecimiento',
                tooltip: 'Correo electróniico',
                orden: 1,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: ['required', 'email'],
                parametrica: null,
                filtro: null,
                maxMinFecha: null,
                size: 12,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: false,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 71
            },
            {
                id: 72,
                campo: 'telefono1',
                tipo: 'text',
                label: 'Teléfono 1',
                tooltip: 'Teléfono 1',
                orden: 1,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: ['required', 'telfCel'],
                parametrica: null,
                filtro: null,
                maxMinFecha: null,
                size: 4,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: false,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 72
            },
            {
                id: 73,
                campo: 'telefono2',
                tipo: 'text',
                label: 'Teléfono 2',
                tooltip: 'Teléfono 2',
                orden: 2,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: ['telfCel'],
                parametrica: null,
                filtro: null,
                maxMinFecha: null,
                size: 4,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: false,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 72
            },
            {
                id: 74,
                campo: 'telefono3',
                tipo: 'text',
                label: 'Teléfono 3',
                tooltip: 'Teléfono 3',
                orden: 3,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: ['telfCel'],
                parametrica: null,
                filtro: null,
                maxMinFecha: null,
                size: 4,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: false,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 72
            },
            {
                id: 75,
                campo: 'codDepartamento',
                tipo: 'select',
                label: 'Departamento',
                tooltip: 'Departamento',
                orden: 1,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: ['required'],
                parametrica: 'parametros/departamentos',
                filtro: null,
                maxMinFecha: null,
                size: 12,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: false,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 73,
                parametricaText: 'nombre',
                campoHijo: 'codProvincia',
            },
            {
                id: 76,
                campo: 'codProvincia',
                tipo: 'select',
                label: 'Provincia',
                tooltip: 'Provincia',
                orden: 2,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: ['required'],
                parametrica: 'parametros/departamentos/territorios?filtro=codigo::id,tipo:provincias',
                filtro: null,
                maxMinFecha: null,
                size: 6,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: false,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 73,
                parametricaText: 'nombre',
                campoPadre: 'codDepartamento',
                campoHijo: 'codMunicipio',
            },
            {
                id: 77,
                campo: 'codMunicipio',
                tipo: 'select',
                label: 'Municipio',
                tooltip: 'Municipio',
                orden: 3,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: ['required'],
                parametrica: 'parametros/departamentos/territorios?filtro=codigo::id,tipo:municipios',
                filtro: null,
                maxMinFecha: null,
                size: 6,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: false,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 73,
                parametricaText: 'nombre',
                campoPadre: 'codProvincia',
            },
            {
                id: 78,
                campo: 'codTipoSubdivisionGeografica',
                tipo: 'select',
                label: 'Tipo de división geográfica',
                tooltip: 'Tipo de división geográfica',
                orden: 4,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: ['required'],
                parametrica: 'parametros/C102_subdivision_geografica/listado',
                filtro: null,
                maxMinFecha: null,
                size: 6,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: false,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 73,
                parametricaText: 'nombre',
            },
            {
                id: 79,
                campo: 'nombreSubdivisionGeografica',
                tipo: 'text',
                label: 'Nombre de la división geográfica',
                tooltip: 'Nombre de la división geográfica',
                orden: 5,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: ['required'],
                parametrica: null,
                filtro: null,
                maxMinFecha: null,
                size: 6,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: false,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 73,
            },
            {
                id: 80,
                campo: 'codTipoVia',
                tipo: 'select',
                label: 'Tipo de vía',
                tooltip: 'Tipo de vía',
                orden: 6,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: ['required'],
                filtro: null,
                parametrica: 'parametros/C103_tipo_via/listado',
                maxMinFecha: null,
                size: 6,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: false,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 73,
                parametricaText: 'nombre',
            },
            {
                id: 81,
                campo: 'nombreVia',
                tipo: 'text',
                label: 'Nombre de la vía',
                tooltip: 'Nombre de la vía',
                orden: 7,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: ['required'],
                parametrica: null,
                filtro: null,
                maxMinFecha: null,
                size: 6,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: false,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 73,
            },
            {
                id: 82,
                campo: 'numeroDomicilio',
                tipo: 'text',
                label: 'Número de domicilio',
                tooltip: 'Número de domicilio',
                orden: 8,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: ['required'],
                parametrica: null,
                filtro: null,
                maxMinFecha: null,
                size: 12,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: false,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 73,
            },
            {
                id: 83,
                campo: 'edificio',
                tipo: 'text',
                label: 'Nombre del edificio',
                tooltip: 'Nombre del edificio',
                orden: 9,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: null,
                parametrica: null,
                filtro: null,
                maxMinFecha: null,
                size: 6,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: false,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 73,
            },
            {
                id: 84,
                campo: 'piso',
                tipo: 'text',
                label: 'Piso',
                tooltip: 'Piso',
                orden: 10,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: null,
                parametrica: null,
                filtro: null,
                maxMinFecha: null,
                size: 6,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: false,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 73,
            },
            {
                id: 85,
                campo: 'codTipoAmbiente',
                tipo: 'select',
                label: 'Tipo ambiente',
                tooltip: 'Tipo ambiente',
                orden: 11,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: ['required'],
                parametrica: 'parametros/C104_tipo_ambiente/listado',
                filtro: null,
                maxMinFecha: null,
                size: 6,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: false,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 73,
                parametricaText: 'nombre',
            },
            {
                id: 86,
                campo: 'numeroNombreAmbiente',
                tipo: 'text',
                label: 'Número o nombre del ambiente',
                tooltip: 'Número o nombre del ambiente',
                orden: 12,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: null,
                parametrica: null,
                filtro: null,
                maxMinFecha: null,
                size: 6,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: false,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 73,
            },
            {
                id: 87,
                campo: 'direccionReferencial',
                tipo: 'textarea',
                label: 'Dirección referencial',
                tooltip: 'Dirección referencial',
                orden: 13,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: null,
                parametrica: null,
                filtro: null,
                maxMinFecha: null,
                size: 12,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: false,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 73,
            },
            {
                id: 88,
                campo: 'ubicacion',
                tipo: 'mapa',
                label: 'Ubicación',
                tooltip: '',
                orden: 13,
                iop: null,
                desabilitado: false,
                valorDefecto: null,
                validacion: null,
                parametrica: null,
                filtro: null,
                maxMinFecha: null,
                size: 12,
                tabla: 'test',
                cantidadMax: 1,
                documentoSoporte: false,
                codigoTipoDocumento: null,
                criterioOpcional: null,
                seccion: 73,
            },
        ];
        const data = items.map((item) => {
            const e = new Campo();
            e.campoPadre = item.campoPadre ? item.campoPadre : null;
            e.campoHijo = item.campoHijo ? item.campoHijo : null;
            e.parametricaText = item.parametricaText ? item.parametricaText : null;
            e.fechaCreacion = new Date();
            e.usuarioCreacion = 'SEEDER';
            e.estado = Status.ACTIVE;
            e.campo = item.campo;
            e.tipo = item.tipo;
            e.label = item.label;
            e.tooltip = item.tooltip;
            e.orden = item.orden;
            e.iop = item.iop;
            e.desabilitado = item.desabilitado;
            e.valorDefecto = item.valorDefecto;
            e.validacion = item.validacion;
            e.parametrica = item.parametrica;
            e.filtro = item.filtro;
            e.maxMinFecha = item.maxMinFecha;
            e.size = item.size;
            e.tabla = item.tabla;
            e.cantidadMax = item.cantidadMax;
            e.documentoSoporte = item.documentoSoporte;
            e.codigoTipoDocumento = item.codigoTipoDocumento;
            e.criterioOpcional = item.criterioOpcional;
            e.id = item.id;
            const s = new Seccion(); s.id = item.seccion;
            e.seccion = s;
            return e;
        });
        await queryRunner.manager.save(data);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    }

}
