export enum RolEnum {
  EMPRESARIO = 'EMPRESARIO',
  ADMINISTRADOR = 'ADMINISTRADOR',
  TECNICO = 'TECNICO',
  TECNICO_VENTANILLA = 'TECNICO_VENTANILLA',
  TECNICO_JURIDICO = 'TECNICO_JURIDICO',
  TODOS = '*',
}
